# Form implementation generated from reading ui file '/home/ewout/p/py/canvas_download/ui/gui.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(422, 524)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 9, 401, 491))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 6, 0, 1, 1)
        self.runPushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.runPushButton.setObjectName("runPushButton")
        self.gridLayout.addWidget(self.runPushButton, 5, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.downloadLockedCheckBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.downloadLockedCheckBox.setObjectName("downloadLockedCheckBox")
        self.horizontalLayout_4.addWidget(self.downloadLockedCheckBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.parallelDownloadsSpinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.parallelDownloadsSpinBox.setMinimum(1)
        self.parallelDownloadsSpinBox.setMaximum(99)
        self.parallelDownloadsSpinBox.setObjectName("parallelDownloadsSpinBox")
        self.horizontalLayout_4.addWidget(self.parallelDownloadsSpinBox)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_4)
        self.gridLayout.addLayout(self.horizontalLayout_3, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.hostInput = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.hostInput.setObjectName("hostInput")
        self.gridLayout.addWidget(self.hostInput, 1, 0, 1, 1)
        self.tokenInput = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.tokenInput.setObjectName("tokenInput")
        self.gridLayout.addWidget(self.tokenInput, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.runPushButton.setText(_translate("MainWindow", "Run"))
        self.downloadLockedCheckBox.setText(_translate("MainWindow", "Download locked files"))
        self.label.setText(_translate("MainWindow", "Parrallel downloads:"))
        self.label_3.setText(_translate("MainWindow", "Token"))
        self.label_2.setText(_translate("MainWindow", "Hostname"))
